spring:
  application:
    name: payment-service-java

  datasource:
    url: jdbc:postgresql://payment-db:5432/payment-service-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  rabbitmq:
    username: USER
    password: 123456
    host: rabbitmq
    port: 5672

server:
  port: 4003

jwt:
  secret-key: supersecretkeysupersecretkey123456
