spring:
  application:
    name: payment-service-java

  rabbitmq:
    username: USER
    password: 123456
    host: rabbitmq
    port: 5672

server:
  port: 4003

rabbitmq:
  queue:
    name: payment_queue


