version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service-db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - base_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-service-db
    ports:
      - "5433:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - base_network

  coworking-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coworking-db
    ports:
      - "5434:5432"
    volumes:
      - coworking_db_data:/var/lib/postgresql/data
    networks:
      - base_network

  booking-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking-db
    ports:
      - "5435:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - base_network


  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - base_network

  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: USER
      RABBITMQ_DEFAULT_PASS: "123456"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - base_network


  api-gateway:
    build: ./apps/api-gateway
    env_file: ./apps/api-gateway/.env
    depends_on:
      - auth-service
    networks:
      - base_network
    ports:
      - "4000:4000"

  auth-service:
    build: ./apps/auth-service
    env_file: ./apps/auth-service/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/auth-service-db?schema=public"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - base_network
    ports:
      - "4001:4001"
      - "51212:51212"


  notification-service:
    build: ./apps/notification-service
    env_file: ./apps/notification-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - base_network


  payment-service:
    build: ./apps/payment-service-java
    container_name: payment-service
    env_file:
      - ./apps/payment-service-java/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - base_network
    ports:
      - "4003:4003"


  back-office:
    build: ./apps/back-office
    env_file: ./apps/back-office/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@coworking-db:5432/coworking-db?schema=public"
    depends_on:
      coworking-db:
        condition: service_started
    networks:
      - base_network
    ports:
      - "4004:4004"
      - "51213:51213"

  booking-service:
    build: ./apps/booking-service
    env_file: ./apps/booking-service/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@booking-db:5432/booking-db?schema=public"
    depends_on:
      booking-db:
        condition: service_started
    networks:
      - base_network
    ports:
      - "4005:4005"
      - "51214:51214"

volumes:
  auth_db_data:
  redis_data:
  rabbitmq_data:
  payment_db_data:
  coworking_db_data:
  booking_db_data:

networks:
  base_network:
    driver: bridge
